### ISSUE TITLE
Convert methods with optional arguments into properties

### ISSUE THREAD

**Issue by EthanChappel** [EthanChappel/Alpyca#1]
Many methods get and set values, which was implemented with optional arguments and ```if``` statements. Here is `Telescope.tracking()` as an example:

```
def tracking(self, Tracking: Optional[bool] = None):
    if Tracking == None:
        return self._get("tracking")
    self._put("tracking", Tracking=Tracking)
```

It would be better to convert these methods into properties, like this:

```
@property
def tracking(self):
    return self._get("tracking")

@tracking.setter
def tracking(self, Tracking: bool):
    self._put("tracking", Tracking=Tracking)
```

**Comment by BobDenny** [comment]
Absolutely. Is this still alive? The normal syntax for properties should be seen by Python programmers.  Also there have been subtle changes to the Alpaca protocol during 2021, with the "final" being published on 2-June-2021. I'd really love to see this updated for app writers and for the  Alpaca changes. See [ASCOM Alpaca API Reference Version 4](https://github.com/ASCOMInitiative/ASCOMRemote/raw/master/Documentation/ASCOM%20Alpaca%20API%20Reference.pdf). I'd volunteer to make the changes. Maybe you generated the code from YAML and PyYAML? Or if Alpaca.py is hand written OK. I'm not a Python expert but I am highly motivated.
